### ISSUE TITLE
order of files to concat is not preserved in output

### ISSUE THREAD

**Issue by radix** [mcler/webpack-concat-plugin#2]
It seems that with this plugin, the order of my files is not preserved as I specify them in filesToConcat. This used to work with the old webpack4 plugin. The files in the final bundle appear to be ordered alphabetically (backbone, bootstrap, clusterize, countUp, etc...).

This is a problem for me because I am building a bundle out of bootstrap and jquery. bootstrap has a top-level check for jQuery's existence, and blows up if it can't find it. Even though I have jQuery as the first file listed in filesToConcat, it is not the first module in the output file.

I traced the code a bit and tried to fix it. `resolveConcatAndUglify` is losing the order of the files by merging them all into one object and then iterating over the keys of the object with `Object.entries(allFiles).forEach(...)` while adding sources to the ConcatSource. I changed it to iterate over the original files to maintain the order:

```
  resolveConcatAndUglify(compilation, files) {
    const allFiles = files.reduce((acc, file) => Object.assign(acc, file), {});
    this.finalFileName = this.getFileName(allFiles);
    const concatSource = new ConcatSource();
    for (const fileObj of files) {
      const name = Object.keys(fileObj)[0];
      const file = fileObj[name];
      concatSource.add(new OriginalSource(file, name));
    }
    compilation.emitAsset(`${this.settings.outputPath}/${this.finalFileName}`, concatSource);
    this.needCreateNewFile = false;
  }
```

Unfortunately the final build is still not ordered correctly, so I'm not sure what else to do.

**Comment by radix** [comment]
I fixed my problem by switching to this plugin: https://www.npmjs.com/package/webpack-merge-and-include-globally

**Comment by radix** [comment]
okay, I have to apologize: I don't think the problem was in the plugin after all, but the way I had my webpack config set up. I had a webpack build section like this:

```javascript
entry: {
    "vendor": VENDOR_FILES,
}
output: {
  path: BIN_DIR,
  filename: "[name].js",
  chunkFormat: "array-push"
},
plugins: [
  new ConcatPlugin({
    fileName: "[name].js",
    filesToConcat: VENDOR_FILES
  })
]
```

The intent here is to have a webpack config that only produces a "vendor.js" file that is used by multiple other webpack configs (through use of "<script src>" tags in my HTML, not through imports or requires). I inherited this webpack config and now I realize how weird it is :)

I think the issue is that because I had an "entry" section containing the vendor files and "output" section writing to "[name].js", it turns out webpack was just writing the vendor file itself and doing it in alphabetical order.

If I changed `fileName` to `vendor.js`, it actually blows up with an error about writing to the same file.

If I changed `fileName` to `vendor2.js`, I discovered that it was writing the file correctly in the order I wanted!

I don't know how, but this used to work in webpack 4. I guess the plugin would overwrite the file after webpack did or something. I dunno.

Anyway, I fixed this by making an "empty.js" (which is empty) and using that as my entry and output, and passing "vendor.js" as my fileName to ConcatPlugin.

I suppose this situation is a little weird; maybe most people don't want to have a separate webpack config (in a multi-config webpack.config.js) that only builds the vendor file. We do it this way because we have multiple other configs in the same file which end up using this same vendor bundle, and we only want to have one vendor bundle.

**Comment by mcler** [comment]
@radix Hi! No matter what - thanks for you participation. Looks like your config worked previously because version for Webpack 4 used non-webpack functionality for parsing, concat and emitting files.

P.S. I'm doing rewrite of plugin. Check out alpha version: https://www.npmjs.com/package/@mcler/webpack-concat-plugin/v/5.0.0-alpha2
