### ISSUE TITLE
glob-parent dependency vulnerability

### ISSUE THREAD

**Issue by guio12** [mcler/webpack-concat-plugin#6]
Hi,

Any chance you fix this glob-parent vulnerability? 'globby' needs to be bumped.

https://github.com/advisories/GHSA-ww39-953v-wcq6

@mcler/webpack-concat-plugin: 4.1.5 -> globby: ^8.0.1 -> fast-glob: ^2.0.2 -> glob-parent: ^3.1.0

<img width="370" alt="image" src="https://user-images.githubusercontent.com/36823544/212875869-6f8df00a-8b6d-4503-9f0f-8a968ce09a33.png">

This is the only vulnerability I cannot fix in my project, this has been the case for quite some time.

Thanks!

**Comment by mcler** [comment]
@guio12 Hi,

I've got rid of it in alpha version https://www.npmjs.com/package/@mcler/webpack-concat-plugin/v/5.0.0-alpha6 but can not say you when I'm going to release the new version
